### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by 9192gks** [JustinaPetr/Weatherbot_Tutorial#103]
(venv) PS C:\Users\Gaurav\Desktop\Orbot> python nlu_model.py
```
c:\users\gaurav\desktop\orbot\rasa\rasa_nlu\__init__.py:12: UserWarning: The 'rasa_nlu' package has been renamed. You should change your imports to use 'rasa.nlu' instead.
  UserWarning,
Traceback (most recent call last):
  File "nlu_model.py", line 19, in <module>
    train_nlu('./data/data.json', 'config_spacy.json', './models/nlu')
  File "nlu_model.py", line 10, in train_nlu
    trainer = Trainer(config.load(config1))
  File "c:\users\gaurav\desktop\orbot\rasa\rasa\nlu\config.py", line 33, in load
    file_config = rasa.utils.io.read_config_file(config)
  File "c:\users\gaurav\desktop\orbot\rasa\rasa\utils\io.py", line 155, in read_config_file
    content = read_yaml(read_file(filename, "utf-8"))
  File "c:\users\gaurav\desktop\orbot\rasa\rasa\utils\io.py", line 132, in read_file
    return f.read()
  File "C:\Python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
```

**Comment by 9192gks** [comment]
The problem was with the "_" in the filename i have provided.Renamed the file config_spacy.json to configspacy.json After that i ran my code it worked smoothly with some few Rasa errors which i fixed it
