### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by felixxoes** [JustinaPetr/Weatherbot_Tutorial#16]
The Full Code version works fine. However, when using the Full Code [Latest release of Rasa NLU and Rasa Core] and launching train_online.py I get the error :

-imac:rasa-full-wetterbot m$ python train_online.py 
Traceback (most recent call last):
  File "train_online.py", line 36, in <module>
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/weathernlu')
  File "/Users/m/anaconda3/lib/python3.6/site-packages/rasa_core/interpreter.py", line 219, in __init__
    self._load_interpreter()
  File "/Users/m/anaconda3/lib/python3.6/site-packages/rasa_core/interpreter.py", line 238, in _load_interpreter
    os.environ))
  File "/Users/m/anaconda3/lib/python3.6/site-packages/rasa_nlu/model.py", line 230, in load
    skip_valdation)
  File "/Users/m/anaconda3/lib/python3.6/site-packages/rasa_nlu/model.py", line 253, in create
    components.validate_requirements(model_metadata.pipeline)
  File "/Users/m/anaconda3/lib/python3.6/site-packages/rasa_nlu/components.py", line 56, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "/Users/m/anaconda3/lib/python3.6/site-packages/rasa_nlu/registry.py", line 125, in get_component_class
    if component_name not in registered_components:
TypeError: unhashable type: 'dict'

What can I do about that?

Thank you-

**Comment by srikar96** [comment]
Are your rasa_core and rasa_nlu the latest version? If not, try upgrading them and run the code. In the Full Code version, both of the modules are old version.

**Comment by JustinaPetr** [comment]
If you are following the video 100%, then you should use the Rasa NLU and Core versions as stated in the requirements.txt file because there were a lot of changes to Rasa NLU and Core since I recorded the video. If you want to use the latest releases of NLU and Core, then use the code from [this directory ](https://github.com/JustinaPetr/Weatherbot_Tutorial/tree/master/Full%20Code%20%5BLatest%20release%20of%20Rasa%20NLU%20and%20Rasa%20Core%5D)
