### ISSUE TITLE
issue while running dialogue_management_model.py 

### ISSUE THREAD

**Issue by hamsa95** [JustinaPetr/Weatherbot_Tutorial#17]
We followed https://jpboost.com/2018/02/06/creating-a-chatbot-with-rasa-nlu-and-rasa-core/ 
when we try to run dialogue_management_model we are facing below issue 
>>>>>>>>>>>>>
/chatbot/sample/weatherbot2/local/lib/python2.7/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from '/home/user/work/projects/chatbot/sample/models/nlu/default/weathernlu/entity_synonyms.json'
  "".format(entity_synonyms_file))
Bot loaded. Type a message and press enter (use '/stop' to exit): 
hai
/home/user/work/projects/chatbot/sample/weatherbot2/local/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user/work/projects/chatbot/sample/weatherbot2/local/lib/python2.7/site-packages/rasa_core/channels/console.py", line 110, in record_messages
    for response in bot_responses:
  File "/home/user/work/projects/chatbot/sample/weatherbot2/local/lib/python2.7/site-packages/rasa_core/channels/console.py", line 67, in send_message_receive_stream
    stream=True) as r:
AttributeError: __exit__

127.0.0.1 - - [2018-09-18 17:15:03] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 153 0.175675
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
IOError: [Errno 32] Broken pipe

Any idea about this issue??

**Comment by lakindu95** [comment]
I got the same issue

**Comment by JustinaPetr** [comment]
Thanks guys, I will look into it ASAP :)

**Comment by PravinrajV** [comment]
I am getting the below error when i run the dialogue_management_model.py
please help:

**************************************
Bot loaded. Type a message and press enter (use '/stop' to exit):

127.0.0.1 - - [2018-09-20 11:39:43] "POST /webhooks/rest/webhook?stream=true&tok
en= HTTP/1.1" 200 154 0.362282
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\threading.py", line 914, in _bootstrap_inn
er
    self.run()
  File "C:\Program Files\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\channels\console.p
y", line 110, in record_messages
    for response in bot_responses:
  File "C:\Program Files\Python35\lib\site-packages\rasa_core\channels\console.p
y", line 67, in send_message_receive_stream
    stream=True) as r:
AttributeError: __exit__

**Comment by tuyendh** [comment]
I get the same error with dialogue_management_model.py:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python36\lib\site-packages\rasa_core\channels\console.py", line 110, in record_messages
    for response in bot_responses:
  File "C:\Program Files\Python36\lib\site-packages\rasa_core\channels\console.py", line 67, in send_message_receive_stream
    stream=True) as r:
AttributeError: __enter__

**Comment by vigneshp826** [comment]
> Thanks guys, I will look into it ASAP :)

@JustinaPetr , is this issue could be related with tensorflow version or AVX architecture absence in the CPU?

**Comment by lakindu95** [comment]
Any updates regarding this issue yet?

**Comment by vigneshp826** [comment]
Anyone solved this issue?

**Comment by vigneshp826** [comment]
I think those who are behind corporate firewall needs to unset the http_proxy environment variable from their shell. It did the trick for me.

**Comment by hamsa95** [comment]
Any updates

**Comment by vigneshp826** [comment]
@hamsa95 Hi, you tried unsetting http_proxy value in the command prompt from which dialogue_mgmt_model script is being executed?

**Comment by hamsa95** [comment]
@vigneshp826 Hi, No, Just working the older version

**Comment by JustinaPetr** [comment]
I am unable to reproduce the error, guys (with a completely fresh installation of python on Ubuntu and Windows10). The only possible causes I can think of:
- env variable mentioned by @vigneshp826 
- Java not installed
- the shell you are using doesn't like spaces in a folder name
Let me know if you tried to fix any of those and if the problem still persists.

**Comment by AbrarAhmedQuresh** [comment]
Guys even i had faced same error, once i installed rasa-sdk and updated to latest version, it worked fine.
