### ISSUE TITLE
Issue while running train online

### ISSUE THREAD

**Issue by samuel-sujith** [JustinaPetr/Weatherbot_Tutorial#32]
I am getting the below error while running the train online program

INFO:rasa_core.policies.keras_policy:Done fitting keras policy model
INFO:rasa_core.training.online:Rasa Core server is up and running on http://localhost:5005
Bot loaded. Type a message and press enter (use '/stop' to exit).
ERROR:rasa_core.training.online:An exception occurred while recording messages.
Traceback (most recent call last):
  File "C:\Users\ssujith5\AppData\Local\Programs\Python\Python35\lib\site-packages\rasa_core\training\online.py", line 845, in record_messages
    domain = retrieve_domain(endpoint)
  File "C:\Users\ssujith5\AppData\Local\Programs\Python\Python35\lib\site-packages\rasa_core\training\online.py", line 109, in retrieve_domain
    return _response_as_json(r)
  File "C:\Users\ssujith5\AppData\Local\Programs\Python\Python35\lib\site-packages\rasa_core\training\online.py", line 62, in _response_as_json
    response.raise_for_status()
  File "C:\Users\ssujith5\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: http://localhost:5005/domain

I am using the endpoint 
action_endpoint = EndpointConfig(url="http://localhost:5005/webhook")
as is given in the code.

**Comment by samuel-sujith** [comment]
I had to disable the proxy in the windows registry and all was working fine.

Thanks,
Sujith.
