### ISSUE TITLE
running command python train_init.py ends in RunTime issue

### ISSUE THREAD

**Issue by karthigithub** [JustinaPetr/Weatherbot_Tutorial#42]
When i try to train the model using train_init.py, i got the below error. Could you please help with this problem. ?

$ python train_init.py
Using TensorFlow backend.
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.umath failed to import
ImportError: numpy.core.umath failed to import
2018-10-24 14:44:58.078003: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr

I have python version 3.6.4 and in requirement txt i have numpy version as numpy==1.13.1 as like in github your project.

**Comment by karthigithub** [comment]
For the above issue, i tried to upgrade the numpy [ pip install numpy --upgrade ] & it got upgraded to numpy-1.15.3. After that running $ python train_init.py got different error...

$ python train_init.py
C:\Users\karthick\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "train_init.py", line 17, in <module>
    agent = Agent('weather_domain.yml', policies = [MemoizationPolicy(), KerasPolicy()])
  File "C:\Users\karthick\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 42, in __init__
    self.domain = self._create_domain(domain)
  File "C:\Users\karthick\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 237, in _create_domain
    return TemplateDomain.load(domain)
  File "C:\Users\karthick\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\domain.py", line 435, in load
    slots = cls.collect_slots(data.get("slots", {}))
  File "C:\Users\karthick\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\domain.py", line 479, in collect_slots
    slot_class = Slot.resolve_by_type(slot_dict[slot_name].get("type"))
AttributeError: 'NoneType' object has no attribute 'get'

Please guide me to how to get rid of this

**Comment by karthigithub** [comment]
> When i try to train the model using train_init.py, i got the below error. Could you please help with this problem. ?
> 
> $ python train_init.py
> Using TensorFlow backend.
> RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
> ImportError: numpy.core.multiarray failed to import
> ImportError: numpy.core.umath failed to import
> ImportError: numpy.core.umath failed to import
> 2018-10-24 14:44:58.078003: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr
> 
> I have python version 3.6.4 and in requirement txt i have numpy version as numpy==1.13.1 as like in github your project.

For the above issue, i tried to upgrade the numpy [ pip install numpy --upgrade ] & it got upgraded to numpy-1.15.3. After that running $ python train_init.py got different error...

$ python train_init.py
C:\Users\karthick\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py_init_.py:34: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
File "train_init.py", line 17, in 
agent = Agent('weather_domain.yml', policies = [MemoizationPolicy(), KerasPolicy()])
File "C:\Users\karthick\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 42, in init
self.domain = self._create_domain(domain)
File "C:\Users\karthick\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 237, in _create_domain
return TemplateDomain.load(domain)
File "C:\Users\karthick\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\domain.py", line 435, in load
slots = cls.collect_slots(data.get("slots", {}))
File "C:\Users\karthick\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\domain.py", line 479, in collect_slots
slot_class = Slot.resolve_by_type(slot_dict[slot_name].get("type"))
AttributeError: 'NoneType' object has no attribute 'get'

Please guide me to how to get rid of this
