### ISSUE TITLE
Issue while running python train_interactive.py

### ISSUE THREAD

**Issue by gaurvipul** [JustinaPetr/Weatherbot_Tutorial#64]
Rasa Core Version: rasa-core                 0.13.0 

Python version: Python 3.6.0 |Anaconda custom (64-bit)

OS Version: 16.04.5 LTS (Xenial Xerus)

**Issue Description:** 
Using "Full Code [Latest release of Rasa NLU and Rasa Core]/"

I got this issue while running: python train_interactive.py

Bot loaded. Visualisation at http://localhost:5005/visualization.html.
Type a message and press enter (press 'Ctr-c' to exit). 
Processed Story Blocks: 100%|███| 10/10 [00:00<00:00, 3131.71it/s, # trackers=1]
ERROR:rasa_core.training.interactive:An exception occurred while recording messages.
Traceback (most recent call last):
  File "/home/vipul/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1206, in record_messages
    _plot_trackers(sender_ids, plot_file, endpoint)
  File "/home/vipul/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1151, in _plot_trackers
    max_history=2)
  File "/home/vipul/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/training/visualization.py", line 448, in visualize_neighborhood
    _merge_equivalent_nodes(graph, max_history)
  File "/home/vipul/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/training/visualization.py", line 203, in _merge_equivalent_nodes
    graph.nodes(data=True)[i])
  File "/home/vipul/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/training/visualization.py", line 170, in _transfer_style
    clazzes = source.get("class", "")
AttributeError: 'tuple' object has no attribute 'get'
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/vipul/anaconda3/envs/rasa/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/vipul/anaconda3/envs/rasa/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vipul/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1206, in record_messages
    _plot_trackers(sender_ids, plot_file, endpoint)
  File "/home/vipul/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1151, in _plot_trackers
    max_history=2)
  File "/home/vipul/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/training/visualization.py", line 448, in visualize_neighborhood
    _merge_equivalent_nodes(graph, max_history)
  File "/home/vipul/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/training/visualization.py", line 203, in _merge_equivalent_nodes
    graph.nodes(data=True)[i])
  File "/home/vipul/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/training/visualization.py", line 170, in _transfer_style
    clazzes = source.get("class", "")
AttributeError: 'tuple' object has no attribute 'get'

**Comment by gaurvipul** [comment]
### solved this issue by re-running 

**pip install rasa_core**
