### ISSUE TITLE
Issue with train_init.py

### ISSUE THREAD

**Issue by SandraAnildas** [JustinaPetr/Weatherbot_Tutorial#74]
When i try to train the model using train_init.py, i got the below error. Could you please help with this problem. ?

Traceback (most recent call last):
  File "train_init.py", line 17, in <module>
    agent = Agent('mentalhealth_domain.yml', policies = [MemoizationPolicy(max_history=5), KerasPolicy()])
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 193, in __init__
    self.domain = self._create_domain(domain)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 648, in _create_domain
    return Domain.load(domain)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\domain.py", line 88, in load
    return cls.from_yaml(read_file(filename))
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\domain.py", line 92, in from_yaml
    cls.validate_domain_yaml(yaml)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\domain.py", line 170, in validate_domain_yaml
    source_data = utils.read_yaml_string(yaml)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\utils.py", line 327, in read_yaml_string
    return yaml_parser.load(string)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\ruamel\yaml\main.py", line 331, in load
    return constructor.get_single_data()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\ruamel\yaml\constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 773, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 852, in _ruamel_yaml.CParser._compose_sequence_node
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.parser.ParserError: while parsing a block collection
  in "<unicode string>", line 22, column 5
did not find expected '-' indicator
  in "<unicode string>", line 23, column 20

**Comment by cobusgreyling** [comment]
What version of Python are you using?

**Comment by SandraAnildas** [comment]
I am using Python 3.6.8
