### ISSUE TITLE
ModuleNotFoundError: No module named 'rasa_nlu.test'

### ISSUE THREAD

**Issue by mayeshc** [JustinaPetr/Weatherbot_Tutorial#95]
When I run dialogue_management_model.py , I am getting this error message "ModuleNotFoundError: No module named 'rasa_nlu.test'". I am using the  code repository "Full Code [Latest release of Rasa NLU and Rasa Core]" . Below is the complete error message. Can you please help?

(weatherbotenv) C:\Users\bluelion\Desktop\Weatherbot>python dialogue_management_model.py
Traceback (most recent call last):
  File "dialogue_management_model.py", line 7, in <module>
    import rasa_core
  File "C:\anaconda3\envs\weatherbotenv\lib\site-packages\rasa_core\__init__.py", line 6, in <module>
    from rasa_core.test import test
  File "C:\anaconda3\envs\weatherbotenv\lib\site-packages\rasa_core\test.py", line 26, in <module>
    from rasa_nlu.test import plot_confusion_matrix, get_evaluation_metrics
ModuleNotFoundError: No module named 'rasa_nlu.test'

**Comment by mayeshc** [comment]
I had a look at the readme.md file and found that the Latest compatible Rasa NLU version is  0.14.4  and Latest compatible Rasa Core version is 0.13.2.
So I modified the requirements.txt to install these version and the issue resolved. Thanks!
